name: main
on: [push]

jobs:
  test:
    strategy:
      matrix:
        go: ["1.20", 1.21]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: Build and test with
      run: go test -v ./...
