name: main
on: [push]

jobs:
  rspec:
    strategy:
      matrix:
        go: [1.13, 1.20]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: go/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: Build and test with
      run: |
